name: Sources release
on:
  push:
    branches: [ "release" ]

jobs:
  build:

    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v4
    
    - name: get sources
      run: for s in lib/*/get; do (cd $(dirname $s) && ./get --sources); done

    - name: Produce artifacts
      run: ./artifacts.sh Sources
      
    - name: upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{env.artifact}}
        path: artifacts/${{env.artifact}}
