name: Linux build
on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "ci" ]
    tags:
      - "v*.*.*"

env:
  BUILD_CONFIGURATION: Debug

jobs:
  build:

    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v4

    - name: set BUILD_CONFIGURATION to Release
      run: echo BUILD_CONFIGURATION=Release >> $GITHUB_ENV
      if: github.ref_type == 'tag'
      
    - name: apt update
      run: sudo apt update

    - name: show tree
      run: ls -lR

    - name: build-dep
      run: ./get --build-dep ${{env.BUILD_CONFIGURATION}}

    - name: install sdl3 system-wide
      run: sudo dpkg -i lib/platform/sdl3-deb/libsdl3-*.deb || true; sudo apt install -f

    - name: configure
      run: ./configure
      
    - name: make
      run: make -j BUILD_TYPE=${{env.BUILD_CONFIGURATION}}

    - name: produce artifact
      run: ./artifact.sh ${{env.BUILD_CONFIGURATION}} >> $GITHUB_ENV
      
    - name: upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{env.artifact}}
        path: artifacts/${{env.artifact}}
        retention-days: 5
