name: Linux build SystemLibs
on:
  push:
    branches: [ "systemlibs" ]

env:
  # Configuration type to build.
  # You can convert this to a build matrix if you need coverage of multiple configuration types.
  # https://docs.github.com/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
  BUILD_CONFIGURATION: SystemLibs

jobs:
  build:

    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v4
    
    - name: apt update
      run: sudo apt update

    - name: build-dep
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: ./get --build-dep ${{env.BUILD_CONFIGURATION}}

    - name: produce artifact
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: ./artifacts.sh ${{env.BUILD_CONFIGURATION}} >> $GITHUB_ENV
      
    - name: upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{env.artifact}}
        path: artifacts/${{env.artifact}}
        retention-days: 5
