name: Sources release
on:
  push:
    branches: [ "rc" ]
    tags:
      - "v*.*.*"

jobs:
  build:

    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v4
    
    - name: get sources
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: ./get --sources

    - name: produce artifact
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: ./artifacts.sh Sources >> $GITHUB_ENV
      
    - name: upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{env.artifact}}
        path: artifacts/${{env.artifact}}
