name: MSBuild

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "ci" ]
    tags:
      - "v*.*.*"

env:
  BUILD_CONFIGURATION: Debug

jobs:
  build:

    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v4

    - name: set BUILD_CONFIGURATION to Release
      run: echo Release >> $GITHUB_ENV
      if: github.ref_type == 'tag'
      
    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    - name: show tree
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: Get-ChildItem -Recurse | Select-Object Mode, LastWriteTime, Length, Name

    - name: build-dep
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: .\build-dep.ps1 ${{env.BUILD_CONFIGURATION}}

    - name: build
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: .\build.ps1 ${{env.BUILD_CONFIGURATION}}

    - name: produce artifact
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: .\artifact.ps1 ${{env.BUILD_CONFIGURATION}} >> $GITHUB_ENV
      
    - name: upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{env.artifact}}
        path: artifacts/${{env.artifact}}
        retention-days: 5
